spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5488/dokuti
    initialization-mode: always
    username: "postgres"
    password: "postgres"
  jpa:
    show-sql: false
    hibernate:
      #ddl-auto: update
      ddl-auto: validate
    properties: 
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: "_documents"
  flyway:
    enabled: true
    #enabled: false
     
storage:
  location: "/tmp/dokuti-local-uploads"
  
#Security Properties
rest:
  security:
    # This property toggles whether Oauth 2.0 based security is enabled. A 'disabled' value removes all security.
    enabled: true
    issuerUri: "http://localhost:5000"
    apiMatcher: "/**"
    cors:
      allowedOrigins: "*"
      allowed-headers: "*"
      allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      maxAge: 3600
      
# This section is only used of rest.security.enabled = true
security:
  oauth2:
    resource:
      id: dokuti
      tokenInfoUri: ${rest.security.issuerUri}/connect/introspect
      userInfoUri: ${rest.security.issuerUri}/connect/userinfo
      jwt:
        keyValue: "-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA1fD6YzaIslie1AQpdyDYyrukqjo4/71G9Us++fDTLMOujuJBgDF2A0p1cvEpc8r3fzwJq2wxfJDXotRp9X/81jDv/uxyO7ifhGcAbxg/wVEz4YmQE5bXFM0IEMhU1VDE17i0CTiwe2WV6G69JSAm7xMChl284zSCZOhlALe25mBg0zkTfmcZIUdkloBsWe94FNsQ0IljLyRiwoEZO0Xrp91eUrUvQm6He3X716zIg+YUzoWk+KVNHuL+pk6Aefy1c+yFia57MTA384ORh8MiGRZ9YuM69uB6oPkFHkwFNWbDW9G+yzcpcXsc0BdQVwsZ9liHbkgRHGthbeC7euG3THEJkaZXAInr2mwcyaNHzCQIOo6cngNOU5S3pLnHNyEM1FG40AYhRj8/uwJ4e//uBbBOUvg7Fo5cnG4FOWLIN35sQUQvht30h+UmG/lb4ualkx/GkDOfyTwejqt2mTLWkblV3vekX7uI+h4M1lFebpAKF602r3qK80PNgPS56BwjGSxLhfllxhN6nhbjPZtaiTfFu0mFTHkRPEo7t2ThDBFMZ7EeA6Ot46MS1D/t+HwjlJ/vnZAH3RcdyUQgp4wJeCJQkd26XlaU5MT3jCFLMj1RLLVhif90gj2mCN+kO/wnSRH3jrrKL5nbgUJNL38D+1RVAfywEdeijIZCbvExC18CAwEAAQ==\n-----END PUBLIC KEY-----"

# This setting exposes all the actuator routes, some of which expose sensitive info. Ensure that only the /health route is exposed
# publically for readiness and liveness probes in non-dev environments.
management:
  endpoints:
    web:
      exposure:
        include: "info, health"
        
logging:
  level:
    root: INFO
    za.co.grindrodbank.dokuti: DEBUG