version: '3'
services:
  dokuti-development-postgresql:
    networks:
      - dokuti-development
    image: "postgres:10.7-alpine"
    restart: always
    ports:
      # Use a non standard port mapping to avoid potential collisions with other Postgres instances running on the host.
      - '5488:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dokuti
  dokuti-identity-server-development:
    networks:
      - dokuti-development
    image: "gbl-baobab-docker-virtual.jfrog.io/identityserver"
    restart: always
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./identity-server-appsettings.json:/app/appsettings.json
    depends_on:
      - dokuti-development-postgresql
    command: sh -c './wait-for.sh dokuti-postgresql-development:5432 -- '
  dokuti-a3s-development:
    networks:
      - dokuti-development
    image: "gbl-baobab-docker-virtual.jfrog.io/a3s"
    restart: always
    ports:
      - 5001:80
    volumes:
      - ./a3s-appsettings.json:/app/appsettings.json
    depends_on:
      - dokuti-development-postgresql
      - dokuti-identity-server-development
    command: sh -c './wait-for.sh dokuti-postgresql-development:5432 -- '
      
networks:
  dokuti-development: