server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/dokuti
    initialization-mode: always
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: validate
    properties: 
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: "_documents"
  flyway:
    enabled: true
    #enabled: false
     
storage:
  location: "/tmp/dokuti-local-uploads"

#Security Properties
rest:
  security:
    # This property toggles whether Oauth 2.0 based security is enabled. A 'disabled' value removes all security.
    enabled: true
    issuerUri: "http://dokuti-a3s-quickstart"
    apiMatcher: "/**"
    cors:
      allowedOrigins: "*"
      allowed-headers: "*"
      allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      maxAge: 3600

# This section is only used of rest.security.enabled = true
security:
  oauth2:
    resource:
      id: dokuti
      tokenInfoUri: ${rest.security.issuerUri}/connect/introspect
      userInfoUri: ${rest.security.issuerUri}/connect/userinfo
      jwt:
        keyValue: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtSi94MClXRcOSSV2WHVCooD1f0ccLZnnMxJ5XdpxtlNQ2RSiFfOlEz+A51Vc3bDZz6bdUFutO5uYN40RY1p6tmxoMGBpRx8yl/2HUeyO5yobpGQ9z+lS+ZPckLn/12wMtj/ojURPyUDFC9Loq9KsvFK+J6HLyaaDtWqb/Tz3akgxlWXIEM4fPreYxPgvdpoWrh4NiE2DKREls7O+Xdrj1PHA7d2KujoowYdHmPw8iBmdC56ryIrHjANOMaUPxpJKAm5LhCjjMXact1KP8ZxDXMpZhiYc/jk/4FBRKnrhTJgmbYbxgWlFmGNJEW+OphAQ1xUBWqonrsEFxUkM8bu1xQIDAQAB\n-----END PUBLIC KEY-----"

# This setting exposes all the actuator routes, some of which expose sensitive info. Ensure that only the /health route is exposed
# publically for readiness and liveness probes in non-dev environments.
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
logging:
  level:
    root: INFO
    za.co.grindrodbank.dokuti: DEBUG
  